### ISSUE TITLE
respecter semver pour le numéro de version

### ISSUE THREAD

**Issue by francoisromain** [MTES-MCT/camino-flux-QGIS#2]
le numéro de version doit respecter cette syntaxe: MAJEUR.MINEUR.CORRECTIF

- numéro de version MAJEUR : changements non rétrocompatibles,
- numéro de version MINEUR : ajouts de fonctionnalités rétrocompatibles,
- numéro de version de CORRECTIF : corrections d’anomalies rétrocompatibles

doc: https://semver.org/lang/fr/

**Comment by NeoBahamut** [comment]
oui, c'est le cas maintenant

**Comment by NeoBahamut** [comment]
Le numéro de version respecte semver désormais.

**Comment by NeoBahamut** [comment]
Francois, je te laisse fermer l'issue

**Comment by francoisromain** [comment]
merci : )
