### ISSUE TITLE
Modification tracker URL

### ISSUE THREAD

**Issue by Gustry** [MTES-MCT/camino-flux-QGIS#3]
Pouvez-vous modifier le tracker pour les bugs et mettre l'URL du GitHub:
* dans le metadata.txt
* et sur plugins.qgis.org dans les métadonnées

**Comment by NeoBahamut** [comment]
ok, on va s'en occuper aujourd'hui

**Comment by WREATCHED** [comment]
Bjr, Ok c'est fait

**Comment by NeoBahamut** [comment]
Bonjour Gustry
Nous avons fait une nouvelle release en tenant compte de vos remarques.
Merci de nous dire si cela convient et auquel cas de fermer l'issue (elle avait été fermé par erreur).
