### ISSUE TITLE
Ne pas enregistrer les fichiers dans le répertoire du plugin

### ISSUE THREAD

**Issue by Gustry** [MTES-MCT/camino-flux-QGIS#4]
J'ai essayé brièvement le plugin, le plugin proprose d'enregistrer les fichiers "camino" dans le dossier du plugin. Je ne suis pas sur que cela soit une bonne idée, car ces fichiers seront écrasés lors d'une MAJ du plugin.

Je vous conseille d'utiliser un autre dossier dans le profile QGIS.
`join(QgsApplication.qgisSettingsDirPath(), 'camino-flux')` ?

Fermez le ticket si non nécessaire

**Comment by NeoBahamut** [comment]
Ok, on regarde aujourd'hui

**Comment by WREATCHED** [comment]
Bjr,
Bonne idée, je travaille dessus pour le modifier et prendre en compte cette modification.

**Comment by NeoBahamut** [comment]
Nous avons pris en compte vos conseils dans la nouvelle release.
Merci de clore cette issue si cela convient.

**Comment by Gustry** [comment]
Je vous fait confiance. C'était plus pour vos utilisateurs ne pas perdre leurs fichiers lors d'une mise  à jour.

**Comment by NeoBahamut** [comment]
Vos remarques étaient de bons conseils, nous vous en remercions
